# Generated by Django 3.2.8 on 2021-10-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
